spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    datasource:
        url: jdbc:mysql://localhost:3306/genericwebapp?serverTimezone=Europe/Berlin
        username: genericwebapp
        password: genericwebapp

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

# if https is needed:
# cd inside_the_maven_project
# keytool -genkeypair -alias tomcat -keyalg RSA -keysize 2048 -keystore keystore.jks -validity 3650 -storepass password

# server:
#   ssl:
#     key-store: keystore.jks
#     key-store-password: password
#     key-store-type: jks
#     key-alias: tomcat
#     key-password: password
#   port: 8443
    
